version: '3'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: "development"
    ports: ["3000:3000"]
    environment:
      RAILS_ENV: "development"
    env_file:
      - docker-compose.env
    depends_on:
      - db
      - elasticsearch
      - redis
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - .:/srv/dfe-tvs:cached
      - node_modules:/srv/dfe-tvs/node_modules
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 'ssl://web:3000?key=config/localhost/https/local.key&cert=config/localhost/https/local.crt'"

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/:cached
    restart: on-failure

  elasticsearch:
    image: elasticsearch
    depends_on:
      - db
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker=docker-cluster
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server

volumes:
  pg_data: {}
  elasticsearch: {}
  node_modules:
